name: Deploy to AWS Spot Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Spot instance
      uses: Tomiphred/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_NAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
          rm -rf /var/www/html/*
          scp -r * ${{ secrets.HOST_NAME }}@${{ secrets.HOST_IP }}:/var/www/html
