name: Deployment to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
      

    - name: Deploy to Spot Instance
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" --exclude='.git*' ./ ${{ secrets.HOST_NAME }}@${{ secrets.HOST_DNS }}:/var/www/html
        ssh -i ~/.ssh/id_rsa $ {{ secrets.HOST_NAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
